### ISSUE TITLE
compute_sparse_matrix.py fails when calling read_csv with unsupported argument

### ISSUE THREAD

**Issue by e-t-k** [ucscHexmap/compute#2]
The current dev version of `compute_sparse_matrix.py crashes when it tries to read the input file because mangle_dupe_calls=False results in a ValueError every time.

Reproduce:
```/bin/bash
# Don't need to create an input file--it will crash before that point

python2.7 compute_sparse_matrix.py --in_file fake.tsv --output_type sparse --log log.txt --out_file output.tsv

Traceback (most recent call last):
  File "compute_sparse_matrix.py", line 462, in <module>
    return_code = main(sys.argv[1:])
  File "compute_sparse_matrix.py", line 409, in main
    replaceNA=replaceNA)
  File "compute_sparse_matrix.py", line 72, in read_tabular
    mangle_dupe_cols=False)
  File "/cluster/home/ekephart/.conda/envs/etkTestEnv/lib/python2.7/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cluster/home/ekephart/.conda/envs/etkTestEnv/lib/python2.7/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/cluster/home/ekephart/.conda/envs/etkTestEnv/lib/python2.7/site-packages/pandas/io/parsers.py", line 751, in __init__
    options = self._get_options_with_defaults(engine)
  File "/cluster/home/ekephart/.conda/envs/etkTestEnv/lib/python2.7/site-packages/pandas/io/parsers.py", line 779, in _get_options_with_defaults
    raise ValueError('Setting mangle_dupe_cols=False is '
ValueError: Setting mangle_dupe_cols=False is not supported yet
```
Pandas documentation, from https://pandas.pydata.org/pandas-docs/stable/io.html#duplicate-names-parsing :
> To prevent users from encountering this problem with duplicate data, a `ValueError` exception is raised if `mangle_dupe_cols != True`

**Comment by mrJeppard** [comment]
Thanks. Parameter is removed from latest code.
